print('\033[32;1mDESAFIO 09 - Tabuada v0\033[m')
print('\033[32;1mALUNO:\033[m \033[36;1mJoaquim Fernandes\033[m')
print('-' * 50)
# -----------------------------------------------------------------------
num = int(input('Digite um número para ver sua Tabuada: '))
print('-'*55)
print('-'*20, f'Tabuada de {num}', '-'*20)
print('-'*55)
print(f'{num} X {1:2} = {num * 1}')
print(f'{num} X {2:2} = {num * 2}')
print(f'{num} X {3:2} = {num * 3}')
print(f'{num} X {4:2} = {num * 4}')
print(f'{num} X {5:2} = {num * 5}')
print(f'{num} X {6:2} = {num * 6}')
print(f'{num} X {7:2} = {num * 7}')
print(f'{num} X {8:2} = {num * 8}')
print(f'{num} X {9:2} = {num * 9}')
print(f'{num} X {10:2} = {num * 10}')
print(f'{num} X {11:2} = {num * 11}')
print(f'{num} X {12:2} = {num * 12}')

# -----------------------------------------------------------------------
