print('\033[32;1mDESAFIO 22 - Analisando Textos\033[m')
print('\033[32;1mALUNO:\033[m \033[36;1mJoaquim Fernandes\033[m')
nome = str(input('Digite seu Nome Completo: ')).strip()
print('======= Analisando o seu Nome =======')
print(f'Seu Nome em Maiúculas é', nome.upper())
print(f'Seu Nome em Minúsculas é', nome.lower())
print(f'Seu Nome ao Todo têm', len(nome)-nome.count(' '), 'Letras')
pnome = nome.split()
print(f'Seu Primeiro Nome é {pnome[0]} e tem {len(pnome[0])} letras')
