print('='*20, ' DESAFIO 3', '='*20)
n = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n))
print('Só têm espaços?', n.isspace())
print('É um Número', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanúmerico', n.isalnum())
print('Está em Maiúscula?', n.isupper())
print('Está em Minúscula?', n.islower())
print('Está Capitalizado?', n.istitle())
