print('='*20, 'DESAFIO 22', '='*20)
nome = str(input('Digite seu nome Completo: ')).strip()
print('-='*5, 'Analisando seu Nome', '-='*5)
print('Todas letras em Maiúscula é {}'.format(nome.upper()))
print('Todas letras em Minúscula é {}'.format(nome.lower()))
print('Seu nome ao todo têm {} letras'.format(len(nome)-nome.count(' ')))
# print('Seu primeiro nome têm {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e têm {} letras'.format(separa[0], len(separa[0])))
print('-='*5, 'Fim da Analise', '-='*5)
