print('='*20, 'DESAFIO 26', '='*20)
frase = str(input('Digite uma Frase: ')).upper().strip()
print('A letra A aparece {} vezes na frase.'.format(frase.count('A')))
print('A primeira letra A apareceu na posicão {}'.format(frase.find('A')+1))
print('A ultima letra A apareceu na posicão {}'.format(frase.rfind('A')+1))
